name = "Unstable North"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e28958166a6550fb9d0052a212591f02263a2070cd1b23d21d0c66cdf23e6c02"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
