name = "Unstable North"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7ab55bcedbf489f609534e30dc8c70d950833266a08e8ab4616ca1b5ab1021c"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
