name = "Iris Shaders"
filename = "iris-mc1.17-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3404/785/iris-mc1.17-1.1.1.jar"
hash-format = "murmur2"
hash = "2509059792"

[update]
[update.curseforge]
file-id = 3404785
project-id = 455508
release-channel = "beta"
