name = "Axolotl Bucket Fix"
filename = "axolotl-item-fix-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3386/413/axolotl-item-fix-1.1.1.jar"
hash-format = "murmur2"
hash = "780369758"

[update]
[update.curseforge]
file-id = 3386413
project-id = 495453
release-channel = "beta"
