name = "BackSlotAddon"
filename = "backslotaddon-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3398/187/backslotaddon-1.0.5.jar"
hash-format = "murmur2"
hash = "2440137574"

[update]
[update.curseforge]
file-id = 3398187
project-id = 411621
release-channel = "beta"
