name = "Better Than Mending"
filename = "betterthanmending-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3213/798/betterthanmending-1.3.0.jar"
hash-format = "murmur2"
hash = "255294584"

[update]
[update.curseforge]
file-id = 3213798
project-id = 264738
release-channel = "beta"
