name = "Falling Leaves (Fabric)"
filename = "fallingleaves-1.7.3+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/359/fallingleaves-1.7.3+1.17.1.jar"
hash-format = "murmur2"
hash = "2126472607"

[update]
[update.curseforge]
file-id = 3420359
project-id = 417510
release-channel = "beta"
