name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.2.1_MC_1.17-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/382/fancymenu_fabric_2.2.1_MC_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "3540253537"

[update]
[update.curseforge]
file-id = 3414382
project-id = 416796
release-channel = "beta"
