name = "Forgotten Recipes - Sculk Sensor, Bundle, Light, Leather and Powder Snow Recipe"
filename = "forgottenrecipes-fabric-1.17.1-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3406/906/forgottenrecipes-fabric-1.17.1-1.0.2.jar"
hash-format = "murmur2"
hash = "2949139094"

[update]
[update.curseforge]
file-id = 3406906
project-id = 496392
release-channel = "beta"
