name = "Grim's Transportables"
filename = "transportables-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/487/transportables-1.0.5.jar"
hash-format = "murmur2"
hash = "3724704120"

[update]
[update.curseforge]
file-id = 3343487
project-id = 473508
release-channel = "beta"
