name = "Illuminations 🔥"
filename = "illuminations-1.6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3401/926/illuminations-1.6.3.jar"
hash-format = "murmur2"
hash = "848792840"

[update]
[update.curseforge]
file-id = 3401926
project-id = 292908
release-channel = "beta"
