name = "Modern Industrialization"
filename = "Modern-Industrialization-0.5.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/292/Modern-Industrialization-0.5.7.jar"
hash-format = "murmur2"
hash = "3727634421"

[update]
[update.curseforge]
file-id = 3419292
project-id = 405388
release-channel = "beta"
