name = "Space Dimensions (Fabric)"
filename = "agape_space_17-0.2.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/891/agape_space_17-0.2.13.jar"
hash-format = "murmur2"
hash = "3847611431"

[update]
[update.curseforge]
file-id = 3414891
project-id = 429841
release-channel = "beta"
