name = "Paxi (Fabric)"
filename = "Paxi-Fabric-1.17-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3391/168/Paxi-Fabric-1.17-1.2.jar"
hash-format = "murmur2"
hash = "1620582131"

[update]
[update.curseforge]
file-id = 3391168
project-id = 418881
release-channel = "beta"
