name = "Scorch (Fabric)"
filename = "scorch-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3379/673/scorch-1.0.2.jar"
hash-format = "murmur2"
hash = "1372015098"

[update]
[update.curseforge]
file-id = 3379673
project-id = 496387
release-channel = "beta"
