name = "Simple Discord RPC [Forge/Fabric]"
filename = "simple-rpc-1.17-2.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/6/simple-rpc-1.17-2.3-fabric.jar"
hash-format = "murmur2"
hash = "1675023402"

[update]
[update.curseforge]
file-id = 3419006
project-id = 411816
release-channel = "beta"
